<template>
	<div class="row double">
		<div class="col-lg-6">
			<div class="todayWeather box">
				<h4>오늘의<br />날씨</h4>
				<span class="pulsate-bck" :class="codeSky"></span>
				<ul>
					<li>{{ data ? data.todayWeather.temperature : "" }}℃</li>
					<li>/</li>
					<li>{{ data ? $t("dashboard.codeSky")[data.todayWeather.codeSky] : "" }}</li>
				</ul>
			</div>
		</div>
		<div class="col-lg-6">
			<div class="detaeWeather box">
				<h4>데이터<br />날씨</h4>
				<span class="codeValue0 pulsate-bck"></span>
				<ul>
					<li>{{ data ? $t("dashboard.codeValue")[data.weatherData.codeValue] : "" }}</li>
				</ul>
			</div>
		</div>
	</div>
</template>

<script>
export default {
	props: ["data"],
	computed: {
		codeSky() {
			if (this.data == null) {
				return "codeSky";
			}

			return "codeSky" + this.data.todayWeather.codeSky;
		}
	}
};
</script>

<style lang="scss">
/*메인대시보드닐씨*/
.double {
	h4 {
		padding: 10px 0 0 25px;
		font-size: 12px;
		margin-top: 20px;
		float: left;
	}
}
.todayWeather,
.detaeWeather {
	height: 110px;
	.pulsate-bck {
		width: 38px;
		height: 38px;
		float: right;
		margin-top: 32px;
		margin-right: 25px;
	}
	ul {
		color: #94a0b4;
		margin-top: 41px;
		margin-right: 7px;
		font-size: 11px;
		float: right;
		li {
			float: left;
		}
	}
}

.todayWeather .codeSky0 {
	background: url("~@/assets/svg/weather_sun.svg") 0 0 no-repeat; //맑음
}
.todayWeather .codeSky1 {
	background: url("~@/assets/svg/weather_cloudsun.svg") 0 0 no-repeat; //구름조금
}
.todayWeather .codeSky2 {
	background: url("~@/assets/svg/weather_cloud.svg") 0 0 no-repeat; //흐림
}
.todayWeather .codeSky3 {
	background: url("~@/assets/svg/weather_rain.svg") 0 0 no-repeat; //비
}
.todayWeather .codeSky4 {
	background: url("~@/assets/svg/weather_snow.svg") 0 0 no-repeat; //눈
}

.detaeWeather .codeValue0 {
	background: url("~@/assets/svg/emo_smile2.svg") 0 0 no-repeat;
}
.detaeWeather .codeValue1 {
	background: url("~@/assets/svg/emo_stop.svg") 0 0 no-repeat;
}
.detaeWeather .codeValue2 {
	background: url("~@/assets/svg/emo_tear.svg") 0 0 no-repeat;
}

@media (max-width: 991px) {
	.double.row .col-lg-6:first-child {
		padding-right: 15px !important;
	}
	.double.row .col-lg-6:last-child {
		padding-left: 15px !important;
	}
}

.pulsate-bck {
	-webkit-animation: pulsate-bck 0.5s ease-in-out;
	animation: pulsate-bck 0.5s ease-in-out;
}
/* ----------------------------------------------
 * Generated by Animista on 2021-4-17 1:55:20
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation pulsate-bck
 * ----------------------------------------
 */
@-webkit-keyframes pulsate-bck {
	0% {
		-webkit-transform: scale(1);
		transform: scale(1);
	}
	50% {
		-webkit-transform: scale(0.9);
		transform: scale(0.9);
	}
	100% {
		-webkit-transform: scale(1);
		transform: scale(1);
	}
}
@keyframes pulsate-bck {
	0% {
		-webkit-transform: scale(1);
		transform: scale(1);
	}
	50% {
		-webkit-transform: scale(0.9);
		transform: scale(0.9);
	}
	100% {
		-webkit-transform: scale(1);
		transform: scale(1);
	}
}
</style>
