<template>
	<div class="row double">
		<div class="col-lg-6">
			<div class="todayWeather box">
				<h4>오늘의<br />날씨</h4>
				<span class="codeSky1 codeRain0 pulsate-bck"></span>
			</div>
		</div>
		<div class="col-lg-6">
			<div class="detaeWeather box">
				<h4>데이터<br />날씨</h4>
				<span class="codeValue0 pulsate-bck"></span>
			</div>
		</div>
	</div>
</template>

<script>
export default {
	props: ["data"],
	data() {
		return {
			chartName: "column"
		};
	}
};
</script>

<style lang="scss">
/*메인대시보드닐씨*/
.double {
	&.row {
		.col-lg-6 {
			&:first-child {
				padding-left: -15px !important;
				padding-right: 7px !important;
			}
			&:last-child {
				padding-left: 8px !important;
				padding-right: -15px !important;
			}
		}
	}
	h4 {
		padding: 10px 0 0 25px;
		font-size: 12px;
		margin-top: 20px;
		float: left;
	}
}
.todayWeather,
.detaeWeather {
	height: 110px;
	.pulsate-bck {
		width: 32px;
		height: 32px;
		float: right;
		margin-top: 32px;
		margin-right: 25px;
	}
}

.todayWeather .codeSky1:before {
	content: "36.5 / 비";
	float: right;
	width: 85px;
	line-height: 32px;
	height: 32px;
	color: #94a0b4;
}

.todayWeather .codeSky1 {
	background: url("~@/assets/svg/weather_sun.svg") 0 0 no-repeat;
}
.detaeWeather .codeValue0 {
	background: url("~@/assets/svg/emo_smile2.svg") 0 0 no-repeat;
}
.detaeWeather .codeValue1 {
	background: url("~@/assets/svg/emo_stop.svg") 0 0 no-repeat;
}
.detaeWeather .codeValue2 {
	background: url("~@/assets/svg/emo_tear.svg") 0 0 no-repeat;
}

@media (max-width: 991px) {
	.double.row .col-lg-6:first-child {
		padding-right: 15px !important;
	}
	.double.row .col-lg-6:last-child {
		padding-left: 15px !important;
	}
}

.pulsate-bck {
	-webkit-animation: pulsate-bck 0.5s ease-in-out;
	animation: pulsate-bck 0.5s ease-in-out;
}
/* ----------------------------------------------
 * Generated by Animista on 2021-4-17 1:55:20
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation pulsate-bck
 * ----------------------------------------
 */
@-webkit-keyframes pulsate-bck {
	0% {
		-webkit-transform: scale(1);
		transform: scale(1);
	}
	50% {
		-webkit-transform: scale(0.9);
		transform: scale(0.9);
	}
	100% {
		-webkit-transform: scale(1);
		transform: scale(1);
	}
}
@keyframes pulsate-bck {
	0% {
		-webkit-transform: scale(1);
		transform: scale(1);
	}
	50% {
		-webkit-transform: scale(0.9);
		transform: scale(0.9);
	}
	100% {
		-webkit-transform: scale(1);
		transform: scale(1);
	}
}
</style>
